### ISSUE TITLE
积分有什么用 这个项目干嘛的

### ISSUE THREAD

**Issue by Achao1213** [ADKcodeXD/sharemd#1]
积分有什么用 这个项目干嘛的

**Comment by ADKcodeXD** [comment]
目前项目方并没有明确的roadmap，可以了解到的是这个项目是通过共享你和gpt的对话数据来给予积分奖励，项目方也是有意将积分作为某种奖赏的凭证。至于后续，关于代币经济学的构建，生态的构建，空投分配的规则等等，都需要持续关注。
